name: text_embedding
channels:
  - conda-forge
dependencies:
  - pip
  - pip:
    - -e .
    - https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.0.0/en_core_web_sm-2.0.0.tar.gz
  - setuptools
  - wheel
  - flake8
  - sphinx
  - click
  - coverage
  - pytest-cov
  - jupyter
  - scikit-learn
  - joblib
  - nb_conda
  - pandas
  - requests
  - matplotlib
  - seaborn
  - gensim=3.4.0
  - python>=3.6
  - spacy

